# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.12-alpine

WORKDIR /app

# Copy all files into the container
COPY . /app

# Upgrade pip and install the package
RUN pip install --upgrade pip && \
    pip install .

# Set default command to run the MCP server
CMD ["python", "src/gitingest-mcp/server.py"]
