[project]
name = "gitingest-mcp"
version = "0.1.0"
description = "Model context protocol server for gitingest"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gitingest>=0.1.4",
    "httpx>=0.28.1",
    "mcp[cli]>=1.3.0",
]